on: push
permissions:
  id-token: write
  pages: write
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: check_out_code
        uses: actions/checkout@v4
      - name: build_code
        run: node build.mjs
      - name: upload_files
        id: uploading
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  deploy-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.uploading.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-gh-pages
    steps:
      - name: deploy_files
        id: deployment
        uses: actions/deploy-pages@v4
